// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3K3z5RXZuSeofDZAh25qzC2_4sQAC7uQ',
    appId: '1:800050778576:android:8cea37f70b173ebd8de9d5',
    messagingSenderId: '800050778576',
    projectId: 'shoply-81086',
    storageBucket: 'shoply-81086.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoSpcJ6xzpD9xNmFh9U4rhg9nmYxXwiwo',
    appId: '1:800050778576:ios:834ed5147384c5eb8de9d5',
    messagingSenderId: '800050778576',
    projectId: 'shoply-81086',
    storageBucket: 'shoply-81086.appspot.com',
    androidClientId: '800050778576-bntb0opcqk6gjdu584bofarv56ftpnt3.apps.googleusercontent.com',
    iosClientId: '800050778576-d18jtd02d5fmb3gbh3d3govjg7mn2jhh.apps.googleusercontent.com',
    iosBundleId: 'com.example.shoplyAdmin',
  );
}
